name: reservation_restaurant
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/best_seller_page/
    - assets/images/home_page/
    - assets/images/home_page/best_seller/
    - assets/images/home_page/our_restaurant/
    - assets/images/home_page/happy_deals/
    - assets/images/authentication/
    - assets/images/authentication/forgot_password/
    - assets/images/logged_in_page/
    - assets/images/logged_out_page/
    - assets/images/reservation_page/
    - assets/images/review_page/
    - assets/images/profile_page/
    - assets/images/about_us_page/
  fonts:
    - family:  Montserrat
      fonts:
        - asset: assets/font/montserrat_weight_100.ttf
          weight: 100
        - asset: assets/font/montserrat_italic_weight_100.ttf
          style: italic
          weight: 100
        - asset: assets/font/montserrat_weight_200.ttf
          weight: 200
        - asset: assets/font/montserrat_weight_300.ttf
          weight: 300
        - asset: assets/font/montserrat_weight_400.ttf
          weight: 400
        - asset: assets/font/montserrat_weight_500.ttf
          weight: 500
        - asset: assets/font/montserrat_weight_600.ttf
          weight: 600
        - asset: assets/font/montserrat_weight_700.ttf
          weight: 700
        - asset: assets/font/montserrat_weight_800.ttf
          weight: 800
        - asset: assets/font/montserrat_weight_900.ttf
          weight: 900

